version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://user:admin@db/postgres"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minio_user"
      MINIO_SECRET_KEY: "minio_password"
      MINIO_BUCKET: "pico"
    env_file:
      - .env
    depends_on:
      - db
      - minio
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
  db:
    image: postgres:11.5-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
